#install_method := "apt"
install_method := "flatpak"

# ptyxis settings
font := "MesloLGS Nerd Font"
fontsize := "12"
opacity := "0.9"
palette := "Catppuccin Mocha"

## Install ptyxis via apt
apt_gsettings := "gsettings"
# Install ptyxis via flatpak
flatpak_gsettings := "flatpak run --command=gsettings app.devsuite.Ptyxis"

gsettings := if install_method == "apt" { apt_gsettings } else { flatpak_gsettings }

gs_base_schema := "org.gnome.Ptyxis"
gs_profile_schema := "org.gnome.Ptyxis.Profile:/org/gnome/Ptyxis/Profiles/PTYXIS_PROFILE/"

ptyxis_wrapper := "/usr/bin/ptyxis.wrapper"

_default:
    @echo "Expressions:"
    @echo "    \e[36minstall_method\e[0m=\e[32m{{ install_method }}\e[0m"
    @echo ""
    @echo "    \e[36mfont\e[0m=\e[32m{{ font }}\e[0m"
    @echo "    \e[36mfontsize\e[0m=\e[32m{{ fontsize }}\e[0m"
    @echo "    \e[36mopacity\e[0m=\e[32m{{ opacity }}\e[0m"
    @echo "    \e[36mpalette\e[0m=\e[32m{{ palette }}\e[0m"
    @echo
    @just --list --unsorted

# Install the Ptyxis terminal
install_requirements: && (_install_requirements install_method)
    @echo -n "🎁  \e[34;1mInstall requirements for \e[0;36m{{ file_stem(justfile_directory()) }}\e[0;34;1m with install method \e[0;36m{{ install_method }}\e[0m\n    "

# Set my prefered settings
settings:
    @profile=$({{ gsettings }} get {{ gs_base_schema }} default-profile-uuid 2>/dev/null); \
    just _settings $(echo $profile)

_check_font:
    @[ "$(fc-match "{{ font }}" -f '%{family}')" = "{{ font }}" ] || (\
    echo " ⚡ \e[31;1mFont \e[0;34;4m{{ font }}\e[0;31;1m is not installed!\e[0m ⚡"; \
    echo "    \e[33;1mUse \e[0;36;3mgetnf\e[0;33;1m to install it.\e[0m"; \
    exit 1; )

_settings PROFILE: _check_font
    @echo -n "🎁  \e[34;1mSettings for \e[0;36m{{ file_stem(justfile_directory()) }}\e[0;34;1m for profile \e[0;36m{{ PROFILE }}\e[0m\n    "
    {{ gsettings }} set {{ gs_base_schema }} font-name "{{font}} {{fontsize}}"
    @echo -n "    "
    {{ gsettings }} set {{ replace(gs_profile_schema, "PTYXIS_PROFILE", PROFILE) }} palette "{{ palette }}"
    @echo -n "    "
    {{ gsettings }} set {{ replace(gs_profile_schema, "PTYXIS_PROFILE", PROFILE) }} opacity {{ opacity }}


_install_requirements METHOD: 
    @[ {{ METHOD }} = "apt" ] || [ {{ METHOD }} = "flatpak" ] || (\
    echo " ⚡ \e[31;1mArgument \e[0;36;4mMETHOD / install_method\e[0;31;1m must be \e[0;36mapt\e[0;31;1m or \e[0;36mflatpak\e[0m ⚡";\
    exit 1; )
    @just _{{ METHOD }}_install_requirements

_apt_install_requirements:
    @sudo apt update && sudo apt install ptyxis -y

_flatpak_install_requirements:
    @if !command -v flatpak >/dev/null 2>&1; then sudo apt update && sudo apt install flatpak -y; fi
    @flatpak install flathub app.devsuite.Ptyxis
    @[ -f {{ ptyxis_wrapper }} ] || (\
    echo '#!/bin/sh' | sudo tee {{ ptyxis_wrapper }} > /dev/null; \
    echo "flatpak run app.devsuite.Ptyxis --new-window" | sudo tee -a {{ ptyxis_wrapper }} > /dev/null; \
    sudo chmod a+x {{ ptyxis_wrapper }}; \
    sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator {{ ptyxis_wrapper }} 10; \
    )
    @echo ""
    @echo " ‼️  \e[33;1mUse \e[0;36;3msudo update-alternatives --config x-terminal-emulator\e[0;33;1m to set default teminal."



 
