-- vim: ft=sql:tw=80:ts=4:sta:sw=4:si:ci
----------------------------------------------------------------- SQL SCRIPT ---
--   NAME
--       <+FILE NAME+><+NOTE+>
--
--   DESCRIPTION
--       <+?DESCRIPTION?+>
--
--   FIRST RELEASE
--       <+DATE+>  <+AUTHOR+>		<+EMAIL+>
--
--   COPYRIGHT (C) <+call:strftime('%Y')+>
--------------------------------------------------------------------------------
--- start main program
    <+CURSOR+>
--------------------------------------------------------------------------------
