set dotenv-filename := "../.env"
set dotenv-load := true

neovim_version := "v0.11.7"
neovim_install_dir := "/opt/neovim" / neovim_version
neovim_appimage := "nvim-linux-x86_64.appimage"
neovim_bin_name := "/usr/local/bin/nvim"
apt_pkgs := "luarocks python3-venv"
nvm_version := "v0.40.7"

# if justfile is run in current directroy recipe_prefix=''
# if justfile is run from parent directroy recipe_prefix='package/'

recipe_prefix := trim_start_match(justfile_directory() + '/', invocation_directory() + '/')
current_package := file_stem(justfile_directory())

_default:
    @just --list --unsorted

_done:
    @echo "${UI_FINISHED}"

# Install neovim dependencies
bootstrap: && _check_dotfiles_bootstraped _install_neovim _install_apt_pkgs _install_nvm_nodejs _mark_bootstraped _mark_done _done
    @echo "${UI_RSYM}Install dependencies for ${UI_RHIC}{{ current_package }}${UI_NORMAL}"

_check_dotfiles_bootstraped:
    @echo -n "${UI_SSYM}Dotfiles bootstraped${UI_NORMAL}"
    @if [ -f "${DOT_DOTFILES_STATE}" ] && jq -e '.bootstrap == true' "${DOT_DOTFILES_STATE}" >/dev/null; then echo " $UI_DONE"; else echo " ${UI_PENDING}";\
    echo "${UI_ASYM}First run: ${UI_AHIC}(cd $(dirname {{ justfile_directory() }}); just bootstrap)${UI_NORMAL}"; \
    exit 1; \
    fi

_install_neovim:
    @echo -n "${UI_SSYM}Install neovim${UI_NORMAL}"
    @if [ -f "{{ neovim_install_dir }}/{{ neovim_appimage }}" ] && [ -f "{{ neovim_bin_name }}" ]; then echo $UI_SKIPPED; else echo ""; \
    ( cd /tmp/; \
    curl -LO https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/{{ neovim_appimage }} >/dev/null 2>&1; \
    chmod +x "/tmp/{{ neovim_appimage }}"; \
    sudo mkdir -p "{{ neovim_install_dir }}"; \
    sudo cp "/tmp/{{ neovim_appimage }}" "{{ neovim_install_dir }}"; \
    sudo chown root:root "{{ neovim_install_dir }}/{{ neovim_appimage }}"; \
    sudo ln -sf "{{ neovim_install_dir }}/{{ neovim_appimage }}" "{{ neovim_bin_name }}"; \
    ) fi

_install_apt_pkgs:
    @echo -n "${UI_SSYM}Install ${UI_SHIC}apt${UI_SCOL} packages${UI_NORMAL}"
    @if dpkg-query -s {{ apt_pkgs }} >/dev/null 2>&1; then echo $UI_SKIPPED; else echo ""; \
    if [ ! -f "${DOT_DOTFILES_STATE}" ] || [ $(( $(date +%s) - $(jq '.apt_update // 0 | tonumber' "${DOT_DOTFILES_STATE}") )) -ge ${DOT_APT_CACHE_MAX_AGE} ]; then \
    echo "${UI_PSYM}Update apt cache${UI_NORMAL}"; \
    if sudo apt-get update >/dev/null; then  \
    echo "$(cat "${DOT_DOTFILES_STATE}" | jq -S --arg ts "$(date +%s)" '.apt_update|=$ts')" > "${DOT_DOTFILES_STATE}" ; \
    sync "${DOT_DOTFILES_STATE}" ; \
    fi; \
    if apt-get -s upgrade | grep -q '^Inst'; then \
    echo "${UI_PSYM}Upgrade apt packages${UI_NORMAL}"; \
    sudo apt-get upgrade -y >/dev/null; \
    fi; \
    fi; \
    echo "${UI_PSYM}Install: ${UI_PHIC}{{ apt_pkgs }}${UI_NORMAL}"; \
    sudo apt-get install {{ apt_pkgs }} -y >/dev/null; \
    fi

_install_nvm_nodejs:
    #!/usr/bin/zsh
    echo -n "${UI_SSYM}Install ${UI_SHIC}nvm${UI_SCOL} and ${UI_SHIC}nodejs${UI_NORMAL}"
    if [ -s "$NVM_DIR/nvm.sh" ]; then echo $UI_SKIPPED; else echo ""
    export NVM_DIR="$HOME/.config/nvm"
    echo "${UI_PSYM}Install: ${UI_PHIC}nvm${UI_NORMAL}"
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash' >/dev/null 2>&1
    source "$NVM_DIR/nvm.sh"
    echo "${UI_PSYM}Install: ${UI_PHIC}nodejs${UI_NORMAL}"
    nvm install --lts >/dev/null 2>&1
    fi

_mark_bootstraped:
    @echo "$(cat "${DOT_DOTFILES_STATE}" | jq --arg pkgname {{ current_package }} '.packages.[$pkgname].bootstrap=true')" > "${DOT_DOTFILES_STATE}"
    @sync "$DOT_DOTFILES_STATE"

_mark_done:
    @echo "$(cat "${DOT_DOTFILES_STATE}" | jq --arg pkgname {{ current_package }} '.packages.[$pkgname].done=true')" > "${DOT_DOTFILES_STATE}"
    @sync "$DOT_DOTFILES_STATE"

# Is there something to install or configure
todo:
    #!/bin/bash
    echo -e "${UI_RSYM}Is there still something todo?${UI_NORMAL}"

    # if not bootstrap -> just bootstrap
    echo -ne "${UI_SSYM}Bootstrap for ${UI_SHIC}{{ current_package }}${UI_NORMAL}"
    if [ -f "${DOT_DOTFILES_STATE}" ] && jq --arg pkgname {{ current_package }} -e '.packages.[$pkgname].bootstrap == true' "${DOT_DOTFILES_STATE}" >/dev/null; then
        echo -e " ${UI_DONE}"
    else
        echo -e " ${UI_PENDING}"
        echo -e "${UI_ASYM}Run: ${UI_AHIC}just {{ recipe_prefix }}bootstrap${UI_NORMAL}"
        exit 0
    fi
