set dotenv-filename := '../.env'
set dotenv-load

apt_pkgs := "tmux tmuxp"

# run apt update if the cache is older the ... minutes
apt_cache_refresh_age := "60"

_default:
    @just --list --unsorted 

_done:
    @echo "${UI_FINISHED}"

# Install tmux dependencies
bootstrap: && _install_apt_pkgs _install_tpm _done
    @echo "${UI_RSYM}Install dependencies for ${UI_RHIC}{{ file_stem(justfile_directory()) }}${UI_NORMAL}"

_install_apt_pkgs:
    @echo -n "${UI_SSYM}Install ${UI_SHIC}apt${UI_SCOL} packages${UI_NORMAL}"
    @if dpkg-query -s {{ apt_pkgs }} >/dev/null 2>&1; then echo $UI_SKIPPED; else echo ""; \
    if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -{{ apt_cache_refresh_age }} 2>/dev/null)" ]; then \
    echo "${UI_PSYM}Update apt cache${UI_NORMAL}"; \
    sudo apt-get update >/dev/null; \
    if apt-get -s upgrade | grep -q '^Inst'; then \
    echo "${UI_PSYM}Upgrade apt packages${UI_NORMAL}"; \
    sudo apt-get upgrade -y >/dev/null; \
    fi; \
    fi; \
    echo "${UI_PSYM}Install: ${UI_PHIC}{{ apt_pkgs }}${UI_NORMAL}"; \
    sudo apt-get install {{ apt_pkgs }} -y >/dev/null; \
    fi

_install_tpm:
    @echo -n "${UI_SSYM}Install ${UI_SHIC}tpm${UI_NORMAL}"
    @if [ -f ~/.tmux/plugins/tpm/tpm ]; then echo $UI_SKIPPED; else echo ""; \
    mkdir -p ~/.tmux/plugins; \
    echo "${UI_PSYM}Git clone ${UI_PHIC}tpm${UI_PCOL} repo${UI_NORMAL}"; \
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm >/dev/null 2>&1; \
    echo "${UI_ASYM}Open ${UI_AHIC}tmux${UI_ACOL} and use the following key-combo to install the plugins:${UI_NORMAL}"; \
    echo "${UI_AIND}${UI_AHIC}<Ctrl>+<a> <Shift>+<i>${UI_NORMAL}"; \
    fi
