set dotenv-filename := "../.env"
set dotenv-load

apt_pkgs := "ptyxis"
# run apt update if the cache is older the ... minutes
apt_cache_refresh_age := "60"

#install_method := "apt"
install_method := "flatpak"
getnf_font := "Meslo"

# ptyxis global settings
use_system_font := "false"
font := "MesloLGS Nerd Font"
fontsize := "12"
default_columns := "80"
default_rows := "24"
restore_session := "false"
restore_window_size := "false"

# ptyxis profile settings
opacity := "0.9"
palette := "Catppuccin Mocha"

## Install ptyxis via apt
apt_gsettings := "gsettings"
# Install ptyxis via flatpak
flatpak_pkgs := "app.devsuite.Ptyxis"
flatpak_gsettings := "flatpak run --command=gsettings " + flatpak_pkgs

gsettings := if install_method == "apt" { apt_gsettings } else { flatpak_gsettings }

gs_base_schema := "org.gnome.Ptyxis"
gs_profile_schema := gs_base_schema + ".Profile:/org/gnome/Ptyxis/Profiles/PTYXIS_PROFILE/"

ptyxis_wrapper := "/usr/bin/ptyxis.wrapper"

_default:
    @echo "Expressions:"
    @echo "  \e[33;3mInstall settings:\e[0m"
    @echo "    \e[36minstall_method\e[0m:      \e[32m{{ install_method }}\e[0m"
    @echo ""
    @echo "  \e[33;3mGlobal Ptyxis settings:\e[0m"
    @echo "    \e[36muse_system_font\e[0m:     \e[32m{{ use_system_font }}\e[0m"
    @echo "    \e[36mfont\e[0m:                \e[32m{{ quote(font) }}\e[0m"
    @echo "    \e[36mfontsize\e[0m:            \e[32m{{ fontsize }}\e[0m"
    @echo "    \e[36mdefault_columns\e[0m:     \e[32m{{ default_columns }}\e[0m"
    @echo "    \e[36mdefault_rows\e[0m:        \e[32m{{ default_rows }}\e[0m"
    @echo "    \e[36mrestore_session\e[0m:     \e[32m{{ restore_session }}\e[0m"
    @echo "    \e[36mrestore_window_size\e[0m: \e[32m{{ restore_window_size }}\e[0m"
    @echo ""
    @echo "  \e[33;3mProfile Ptyxis settings:\e[0m"
    @echo "    \e[36mopacity\e[0m:             \e[32m{{ opacity }}\e[0m"
    @echo "    \e[36mpalette\e[0m:             \e[32m{{ quote(palette) }}\e[0m"
    @echo
    @just --list --unsorted

_done:
    @echo "${UI_FINISHED}"

# Install ptyxis dependencies
bootstrap: && (_install_requirements install_method) _install_font _hint_set_default_terminal _done
    @echo "${UI_RSYM}Install dependencies for ${UI_RHIC}{{ file_stem(justfile_directory()) }}${UI_RCOL} with install method ${UI_RHIC}{{ install_method }}${UI_NORMAL}"

_install_font:
    @echo -n "${UI_SSYM}Install font ${UI_SHIC}{{ font }}${UI_NORMAL}"
    @if [ "$(fc-match "{{ font }}" -f '%{family}')" = "{{ font }}" ]; then echo $UI_SKIPPED; else echo ""; \
    ~/.local/bin/getnf -i "{{ getnf_font }}" | paste /dev/null -; \
    fi

_install_requirements METHOD:
    @[ {{ METHOD }} = "apt" ] || [ {{ METHOD }} = "flatpak" ] || (\
    echo "${UI_SERS}Argument ${UI_SHIC}METHOD / install_method${UI_SWAC} must be ${UI_SHIC}apt${UI_SWAC} or ${UI_SHIC}flatpak${UI_SERE}";\
    exit 1; )
    @just _{{ METHOD }}_install_requirements

_apt_install_requirements:
    @echo -n "${UI_SSYM}Install ${UI_SHIC}apt${UI_SCOL} packages${UI_NORMAL}"
    @if dpkg-query -s {{ apt_pkgs }} >/dev/null 2>&1; then echo $UI_SKIPPED; else echo ""; \
    if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -{{ apt_cache_refresh_age }} 2>/dev/null)" ]; then \
    echo "${UI_PSYM}Update apt cache${UI_NORMAL}"; \
    sudo apt-get update >/dev/null; \
    if apt-get -s upgrade | grep -q '^Inst'; then \
    echo "${UI_PSYM}Upgrade apt packages${UI_NORMAL}"; \
    sudo apt-get upgrade -y >/dev/null; \
    fi; \
    fi; \
    echo "${UI_PSYM}Install: ${UI_PHIC}{{ apt_pkgs }}${UI_NORMAL}"; \
    sudo apt-get install {{ apt_pkgs }} -y >/dev/null; \
    fi

_flatpak_apt_install:
    @echo -n "${UI_SSYM}Install ${UI_SHIC}flatpak${UI_SCOL}apt package${UI_NORMAL}"
    @if dpkg-query -s flatpak >/dev/null 2>&1; then echo $UI_SKIPPED; else echo ""; \
    if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -{{ apt_cache_refresh_age }} 2>/dev/null)" ]; then \
    echo "${UI_PSYM}Update apt cache${UI_NORMAL}"; \
    sudo apt-get update >/dev/null; \
    if apt-get -s upgrade | grep -q '^Inst'; then \
    echo "${UI_PSYM}Upgrade apt packages${UI_NORMAL}"; \
    sudo apt-get upgrade -y >/dev/null; \
    fi; \
    fi; \
    echo "${UI_PSYM}Install: ${UI_PHIC}flatpak${UI_NORMAL}"; \
    sudo apt-get install flatpak -y >/dev/null; \
    echo "${UI_PSYM}Configure remote: ${UI_PHIC}flathub.org${UI_NORMAL}"; \
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo; \
    fi

_flatpak_install_requirements: _flatpak_apt_install
    @echo -n "${UI_SSYM}Install ${UI_SHIC}{{ flatpak_pkgs }}${UI_NORMAL}"
    @if flatpak info {{ flatpak_pkgs }} -r >/dev/null 2>&1; then echo $UI_SKIPPED; else echo ""; \
    flatpak install --noninteractive flathub {{ flatpak_pkgs }} >/dev/null 2>&1; \
    if [ ! -f {{ ptyxis_wrapper }} ]; then \
    echo "${UI_PSYM}Install wrapper script: ${UI_PHIC}{{ ptyxis_wrapper }}${UI_NORMAL}"; \
    echo "#!/bin/sh" | sudo tee {{ ptyxis_wrapper }} > /dev/null; \
    echo "flatpak run app.devsuite.Ptyxis --new-window" | sudo tee -a {{ ptyxis_wrapper }} > /dev/null; \
    sudo chmod a+x {{ ptyxis_wrapper }}; \
    echo "${UI_PSYM}Register wrapper for ${UI_PHIC}update-alternatives${UI_NORMAL}"; \
    sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator {{ ptyxis_wrapper }} 10; \
    fi; \
    fi

_hint_set_default_terminal:
    @echo "${UI_SSYM}Set default terminal"
    @echo "${UI_ASYM}To set ptyxis as your default teminal run:"
    @echo "${UI_AIND}${UI_AHIC}sudo update-alternatives --config x-terminal-emulator${UI_NORMAL}"

# Set my prefered settings
settings: && _done
    @profile=$({{ gsettings }} get {{ gs_base_schema }} default-profile-uuid 2>/dev/null | sed "s/'//g"); \
    echo "${UI_RSYM}Settings for ${UI_RHIC}{{ file_stem(justfile_directory()) }}${UI_RCOL} for profile ${UI_RHIC}${profile}${UI_NORMAL}"; \
    just _settings $profile

_settings PROFILE: _install_font
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}use-system-font${UI_NORMAL} → ${UI_SHIC}{{ use_system_font }}${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} use-system-font {{ use_system_font }}
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}font-name${UI_NORMAL} → ${UI_SHIC}\"{{ font }} {{ fontsize }}\"${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} font-name "{{ font }} {{ fontsize }}"
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}default-columns${UI_NORMAL} → ${UI_SHIC}{{ default_columns }}${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} default-columns {{ default_columns }}
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}default-rows${UI_NORMAL} → ${UI_SHIC}{{ default_rows }}${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} default-rows {{ default_rows }}
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}restore-session${UI_NORMAL} → ${UI_SHIC}{{ restore_session }}${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} restore-session {{ restore_session }}
    @echo "${UI_SSYM}Set globaly: ${UI_SHIC}restore-window-size${UI_NORMAL} → ${UI_SHIC}{{ restore_window_size }}${UI_NORMAL}"
    @{{ gsettings }} set {{ gs_base_schema }} restore-window-size {{ restore_window_size }}
    @echo "${UI_SSYM}Set for defaulp profil: ${UI_SHIC}palette${UI_NORMAL} → ${UI_SHIC}\"{{ palette }}\"${UI_NORMAL}"
    @{{ gsettings }} set {{ replace(gs_profile_schema, "PTYXIS_PROFILE", PROFILE) }} palette "{{ palette }}"
    @echo "${UI_SSYM}Set for defaulp profil: ${UI_SHIC}opacity${UI_NORMAL} → ${UI_SHIC}{{ opacity }}${UI_NORMAL}"
    @{{ gsettings }} set {{ replace(gs_profile_schema, "PTYXIS_PROFILE", PROFILE) }} opacity {{ opacity }}
